apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation # find all pods with this label

  template: # configuration for the pod
    metadata:
      labels:
        app: moderation

    spec:
      containers:
        - name: moderation
          image: gggfox/moderation:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4003
