apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts # find all pods with this label

  template: # configuration for the pod
    metadata:
      labels:
        app: posts

    spec:
      containers:
        - name: posts
          image: gggfox/posts:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # Node port service port
      targetPort: 4000 # actual container port
