@base_url=http://localhost:3200

GET {{base_url}}/todos HTTP/1.1
Content-Type: application/json

###

POST {{base_url}} HTTP/1.1
content-type: application/json

{
  "title": "dune",
  "content": "I love this"
}
